<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ceklis_icon</name>
   <tag></tag>
   <elementGuidId>da69698c-0793-40bb-9c5f-64bc5b280f26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sa-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[10]/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4df08dba-35e6-4f17-a5ce-b0c09c0e5c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sa-placeholder</value>
      <webElementGuid>1a3771b1-2cbe-4945-aec2-506f1707013a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open stop-scrolling&quot;]/div[@class=&quot;sweet-alert  showSweetAlert visible&quot;]/div[@class=&quot;sa-icon sa-success animate&quot;]/div[@class=&quot;sa-placeholder&quot;]</value>
      <webElementGuid>06d0219d-61ce-42c2-bb18-bb18bd66e91f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[4]/div</value>
      <webElementGuid>8f77b403-253e-40d4-9ec0-bd40d57ab766</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
